spring.application.name=learningarea


# ------------------------  DATABASES ------------------------
# AUTH DATABASE
spring.datasource.auth.jdbc-url=jdbc:mysql://switchback.proxy.rlwy.net:40089/auth_db?createDatabaseIfNotExist=true
spring.datasource.auth.username=root
spring.datasource.auth.password=EHdlppkgGJSQcSIDdVATqwsmBHHiPmUU

# CHENNAI DATABASE
spring.datasource.chennai.jdbc-url=jdbc:mysql://switchback.proxy.rlwy.net:40089/careerdb_chennai?createDatabaseIfNotExist=true
spring.datasource.chennai.username=root
spring.datasource.chennai.password=EHdlppkgGJSQcSIDdVATqwsmBHHiPmUU

# MADURAI DATABASE
spring.datasource.madurai.jdbc-url=jdbc:mysql://switchback.proxy.rlwy.net:40089/careerdb_madurai?createDatabaseIfNotExist=true
spring.datasource.madurai.username=root
spring.datasource.madurai.password=EHdlppkgGJSQcSIDdVATqwsmBHHiPmUU

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

! Gmail SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projecttrail1230@gmail.com
spring.mail.password=pgwu kxts mmdp ipay   # <-- your new App Password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


