spring.application.name=learningarea


# ------------------------  DATABASES ------------------------
# AUTH DATABASE
# AUTH DATABASE
spring.datasource.auth.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/auth_db?createDatabaseIfNotExist=true
spring.datasource.auth.username=${MYSQL_USER}
spring.datasource.auth.password=${MYSQL_PASSWORD}

# CHENNAI DATABASE
spring.datasource.chennai.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/careerdb_chennai?createDatabaseIfNotExist=true
spring.datasource.chennai.username=${MYSQL_USER}
spring.datasource.chennai.password=${MYSQL_PASSWORD}

# MADURAI DATABASE
spring.datasource.madurai.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/careerdb_madurai?createDatabaseIfNotExist=true
spring.datasource.madurai.username=${MYSQL_USER}
spring.datasource.madurai.password=${MYSQL_PASSWORD}

# COMMON SETTINGS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


! Gmail SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projecttrail1230@gmail.com
spring.mail.password=pgwu kxts mmdp ipay   # <-- your new App Password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


