spring.application.name=learningarea

# ------------------------  DATABASES ------------------------
# AUTH DATABASE
spring.datasource.auth.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/auth_db
spring.datasource.auth.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.auth.password=${SPRING_DATASOURCE_PASSWORD}

# CHENNAI DATABASE
spring.datasource.chennai.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/careerdb_chennai
spring.datasource.chennai.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.chennai.password=${SPRING_DATASOURCE_PASSWORD}

# MADURAI DATABASE
spring.datasource.madurai.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/careerdb_madurai
spring.datasource.madurai.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.madurai.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

! Gmail SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projecttrail1230@gmail.com
spring.mail.password=cflm jvco zkxe efri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.ssl.trust=*
